const breedNames = [
  'Akhal-Teke',
  'American Quarter Horse',
  'American Saddlebred',
  'Andalusian horse',
  'Arabian horse',
  'Appaloosa',
  'Australian Stock Horse',
  'Brumby',
  'Bashkir Curly',
  'Budyonny horse',
  'Camargue horse',
  'Canadian horse',
  'Chincoteague Pony',
  'Cleveland Bay',
  'Connemara pony',
  'Criollo horse',
  'Clydesdale horse',
  'Dales Pony',
  'Dartmoor Pony',
  'Exmoor pony',
  'Falabella',
  'Fjord horse',
  'Friesian horse',
  'Garrano',
  'Gypsy horse',
  'Hackney horse',
  'Hanoverian horse',
  'Holsteiner',
  'Icelandic horse',
  'Irish Draught',
  'Kiger Mustang',
  'Lipizzan',
  'Lusitano',
  'Marwari horse',
  'Mangalarga Marchador',
  'Missouri Fox Trotter',
  'Morgan horse',
  'Mustang',
  'New Forest Pony',
  'Noriker',
  'Orlov Trotter',
  'Paint horse',
  'Paso Fino',
  'Percheron',
  'Rocky Mountain Horse',
  'Russian Don',
  'Shire horse',
  'Standardbred',
  'Spotted Saddle Horse',
  'Shetland pony',
  'Suffolk Punch',
  'Tarpan',
  'Tennessee Walking Horse',
  'Thoroughbred',
  'Trakehner',
  'Welsh pony',
];
  
export default breedNames;
