const breedNames = [
    'Arabian horse',
    'Thoroughbred',
    'Friesian horse',
    'Andalusian horse',
    'Appaloosa',
    'Clydesdale horse',
    'Mustang',
    'Shire horse',
    'Shetland pony',
    'Morgan horse',
    'American Quarter Horse',
    'Paint horse',
    'Tennessee Walking Horse',
    'Hanoverian horse',
    'Lipizzan',
    'Akhal-Teke',
    'Falabella',
    'Hackney horse',
    'Percheron',
    'Paso Fino',
    'Exmoor pony',
    'Welsh pony',
    'Icelandic horse',
    'Marwari horse',
    'Noriker',
    'Trakehner',
    'Haflinger',
    'Rocky Mountain Horse',
    'Gypsy horse',
    'Lusitano',
    'Connemara pony',
    'Camargue horse',
    'Australian Stock Horse',
    'Cleveland Bay',
    'Brumby',
    'Criollo horse',
    'Holsteiner',
    'Orlov Trotter',
    'Tarpan',
  ];
  
  export default breedNames;